Less 18 badges
IljaBekirov/TestGuru pull request #19
Opened 2020-12-27 18:09 UTC by IljaBekirov

2020-12-28 08:29 UTC, BubuntuClu requested changes

2020-12-28 08:29 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    params[:badge][:condition] = params[:badge][params[:badge][:rule_type]]
как минимум это можно вынести в метод. у тебя несколько раз этот код повторяется.
почему вообще пришлось делать такой костыль?

2020-12-28 08:29 UTC, BubuntuClu commented on app/models/badge.rb
> +    all_categories: { desc: 'Все тесты категории', sel: Category.all.map { |a| [a.title, a.id] } },
ты запустил приложение, у тебя рассчиталось значение для константы. а потом, когда ты добавил новую категорию, у тебя константа обновится? 
лучше на методы разбить(потом в будущем эти методы можно будет кешировать чтобы каждый раз не считать), а пока пусть считается каждый раз

2020-12-28 08:29 UTC, BubuntuClu commented on app/helpers/badges_helper.rb
> +    if badge.new_record?
это конечно жесть) попробуй лучше на `case` переписать.

2020-12-28 08:29 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      check_badges(@test_passage) if @test_passage.completed?
```
 if @test_passage.completed?
    check_badges(@test_passage) if @test_passage.completed?
...
```
ээээ, закрыл дверь на ключ, отошел на два метра и решил еще раз убедиться что закрыл дверь?)

или тут должно быть `@test_passage.successful?`?

2020-12-28 08:29 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @test_passage.successful? &&
это стоит проверять при вызове самого сервиса. если не был успешно пройден, то и выдавать нечего

2020-12-28 08:29 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    test_passages.count == condition && condition == test_passages.map { |tp| tp if tp.successful? }.compact.count
`test_passages.map { |tp| tp if tp.successful? }.compact.` не стоит лишний раз рубишный метод гонять, когда можно запросом все сделать. добавь флаг в таблицу, что успешно пройден тест. можешь добавить скоуп на это поле. и получиться очень легкий запрос

2020-12-28 08:29 UTC, BubuntuClu commented on db/migrate/20201223171251_add_column_to_badges.rb
> +class AddColumnToBadges < ActiveRecord::Migration[6.0]
если забыл поле и ты в своей ветке еще находишься, зачем миграции плодить? откати создание таблицы и допиши там нужные поля и накати

2020-12-28 08:29 UTC, BubuntuClu commented on db/migrate/20201223195930_add_column_conditions_to_badges.rb
> +  def change
и тут тоже

2020-12-28 08:29 UTC, BubuntuClu commented on app/views/admin/badges/_form.html.erb
> +    if (option === 'all_categories') {
давай тут тоже на свитч перепишем. не нравятся мне эти else if. оператор теряется в этой стене текста

2020-12-28 22:21 UTC, IljaBekirov commented on app/controllers/admin/badges_controller.rb
> +    params[:badge][:condition] = params[:badge][params[:badge][:rule_type]]
> почему вообще пришлось делать такой костыль?

это из-за того, что во вьюхе есть 3 разных поля, и выводится js по условию. А в парамс передаются все три поля, поэтому выбираю из того, какой выводится.

![изображение](https://user-images.githubusercontent.com/41266532/103246305-11e22780-4974-11eb-83a8-726ab75405d5.png)

> как минимум это можно вынести в метод. у тебя несколько раз этот код повторяется.

Вынес в отдельный метод

2021-01-11 21:29 UTC, IljaBekirov commented on app/models/badge.rb
> +    all_categories: { desc: 'Все тесты категории', sel: Category.all.map { |a| [a.title, a.id] } },
Сделал

2021-01-11 21:51 UTC, IljaBekirov commented on app/controllers/test_passages_controller.rb
> +      check_badges(@test_passage) if @test_passage.completed?
Да, метод проверки на получение бейджей должен вызываться только в случае положительного прохождения теста.

2021-01-11 21:53 UTC, IljaBekirov commented on app/services/badge_service.rb
> +    @test_passage.successful? &&
да, понял. Поправил

2021-01-11 22:14 UTC, IljaBekirov commented on app/services/badge_service.rb
> +    test_passages.count == condition && condition == test_passages.map { |tp| tp if tp.successful? }.compact.count
Добавил флаг в таблицу и сделал скоуп

2021-01-11 22:36 UTC, IljaBekirov commented on db/migrate/20201223171251_add_column_to_badges.rb
> +class AddColumnToBadges < ActiveRecord::Migration[6.0]
поправил миграции

2021-01-11 22:36 UTC, IljaBekirov commented on db/migrate/20201223195930_add_column_conditions_to_badges.rb
> +  def change
поправил миграции

2021-01-11 22:43 UTC, IljaBekirov commented on app/views/admin/badges/_form.html.erb
> +    if (option === 'all_categories') {
переписал на switch/case

2021-01-12 06:57 UTC, BubuntuClu requested changes

2021-01-12 06:57 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    save!
`rescue` блок нужен либо убери `!`
а вот в имя метода можно добавить `!`, так как ты меняешь состояние объекта

2021-01-12 06:57 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    test_passages.count == condition && condition == test_passages.map { |tp| tp if tp.pass }.compact.count
от map надо избавиться. у тебя уже есть поле для успешного прохождения, по нему сделай запрос.
и вообще тут должно быть только одно условие. количество успешных уникальных прохождений должно быть равно 1(если это проверка первого прохождения)

2021-01-12 15:20 UTC, IljaBekirov commented on app/models/test_passage.rb
> +    save!
Поправил

2021-01-12 16:02 UTC, IljaBekirov commented on app/services/badge_service.rb
> +    test_passages.count == condition && condition == test_passages.map { |tp| tp if tp.pass }.compact.count
избавился от map путём замены на запрос.
Да, сразу думал сделать, как проверку первого прохождения, а потом подумал, чтоб можно было настраивать

2021-01-12 16:16 UTC, merged