Less 18 timer
IljaBekirov/TestGuru pull request #20
Opened 2020-12-27 18:09 UTC by IljaBekirov

2020-12-28 08:19 UTC, BubuntuClu requested changes

2020-12-28 08:19 UTC, BubuntuClu commented on app/javascript/utilities/timer.js
> +        window.location.replace('/test_passages/' + userTestId + '/result');
на мой взгляд, лучше сабмит формы сделать. вдруг пользователь выбрал ответ, но не успел нажать кнопку. в этом случае ответ же должен пройти проверку, как мне кажется

2020-12-28 08:19 UTC, BubuntuClu commented on db/schema.rb
> +  create_table 'badges', force: :cascade do |t|
код который не относится к этой фиче, его тут быть не должно

2020-12-28 08:19 UTC, BubuntuClu commented on app/javascript/utilities/timer.js
> +document.addEventListener('turbolinks:load', function() {
если отключить выполнение js кода на странице, твой таймер не будет работать. нужно добавить проверку и на бэке

2020-12-28 20:57 UTC, IljaBekirov commented on app/javascript/utilities/timer.js
> +        window.location.replace('/test_passages/' + userTestId + '/result');
> на мой взгляд, лучше сабмит формы сделать. вдруг пользователь выбрал ответ, но не успел нажать кнопку. в этом случае ответ же должен пройти проверку, как мне кажется

Я просто думал, что логика такая, если время заканчивается, то тест заканчивается совсем и пользователя перебрасывает на страницу результата.
У меня был перед этим коммит, где я делал сабмит, в таком случае пользователя отправляло просто на следующий вопрос, если такой есть в тесте, а не результирующую страницу.

2020-12-28 20:59 UTC, IljaBekirov commented on db/schema.rb
> +  create_table 'badges', force: :cascade do |t|
> код который не относится к этой фиче, его тут быть не должно

убрал

2020-12-28 22:04 UTC, IljaBekirov commented on app/javascript/utilities/timer.js
> +document.addEventListener('turbolinks:load', function() {
> если отключить выполнение js кода на странице, твой таймер не будет работать. нужно добавить проверку и на бэке

Добавил проверку на бэке

2020-12-29 09:07 UTC, BubuntuClu commented on app/javascript/utilities/timer.js
> +        window.location.replace('/test_passages/' + userTestId + '/result');
для этого надо логику чуть подпилить было, чтобы перекидывало на результат

2021-01-12 16:09 UTC, merged